facebook_connection:
    resource: "@FacebookConnectionBundle/Controller/"
    type:     annotation
    prefix:   /login

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout