app:
    resource: '@AppBundle/Controller/'
    type: annotation

facebook_connection:
    resource: "@FacebookConnectionBundle/Controller/"
    type:     annotation
    prefix:   /

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }