security:
    providers:
        in_memory:
            memory: ~
        provider.facebook_user:
            id: facebook_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_doc:
            pattern: ^/api/doc
            security: false

        secured_area:
            pattern: ^/login
            stateless: false
            simple_preauth:
                authenticator: facebook_authenticator
            provider: provider.facebook_user
            logout:
                path:   /login/logout
                target: /

        api:
            pattern: ^/api
            anonymous: false
            stateless: true
            simple_preauth:
                authenticator: facebook_authenticator
            provider: provider.facebook_user

        api_doc:
            pattern: ^/api/doc
            security: false

        main:
            anonymous: ~
