security:
    providers:
        in_memory:
            memory: ~
        provider.facebook_user:
            id: facebook_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/connection
            stateless: true
            simple_preauth:
                authenticator: facebook_authenticator
            provider: provider.facebook_user

        main:
            pattern: ^/
            anonymous: true
