services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    FacebookConnectionBundle\Controller\:
        resource: '../../src/FacebookConnectionBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    user_manager:
        class: FacebookConnectionBundle\Manager\UserManager

    facebook_authenticator: '@FacebookConnectionBundle\Security\FacebookAuthenticator'
    FacebookConnectionBundle\Security\FacebookAuthenticator:
        arguments:
            $client_id: "%client_id%"
            $client_secret: "%client_secret%"
            $redirect_uri: "%redirect_uri%"

    facebook_user_provider:
        class: FacebookConnectionBundle\Security\FacebookUserProvider
        arguments: ["@csa_guzzle.client.facebook_api", "@jms_serializer", "@user_manager"]

    GuzzleHttp\Client: '@csa_guzzle.client.facebook_api'
