<?php

namespace FacebookConnectionBundle\Controller;

use FacebookConnectionBundle\Entity\User;
use FacebookConnectionBundle\Exception\ResourceValidationException;
use FacebookConnectionBundle\Exception\UserExistException;
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations\Get;
use FOS\RestBundle\Controller\Annotations\Post;
use FOS\RestBundle\Controller\Annotations\Delete;
use FOS\RestBundle\Controller\Annotations\View;
use Nelmio\ApiDocBundle\Annotation\Model;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Validator\ConstraintViolationList;
use Swagger\Annotations as SWG;

class UserController extends FOSRestController
{
    // CREATE
    /**
     * @Post(
     *     path="/api/users",
     *     name="app_user_creation"
     * )
     * @ParamConverter("user", converter="fos_rest.request_body")
     *
     * @View(StatusCode=201)
     *
     * @Security("has_role('ROLE_USER')")
     *
     * @param User $user
     * @param ConstraintViolationList $violations
     * @return mixed
     * @throws
     *
     * @SWG\Parameter(
     *     name="id",
     *     in="header",
     *     type="string",
     *     description="AutoGenerated unique id. Don't have to type it"
     * )
     * @SWG\Parameter(
     *     name="username",
     *     in="header",
     *     type="string",
     *     description="User's username or fullname. Have to be unique",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="email",
     *     in="header",
     *     type="string",
     *     description="User's email.",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="gender",
     *     in="header",
     *     type="string",
     *     description="User's gender. ''male'' or ''female''",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="first_name",
     *     in="header",
     *     type="string",
     *     description="User's first name.",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="last_name",
     *     in="header",
     *     type="string",
     *     description="User's last name.",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="roles",
     *     in="header",
     *     type="string",
     *     description="User's role. Have to type '' ''roles'': ''[\\''ROLE_USER\\'']'' ''",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="facebookId",
     *     in="header",
     *     type="string",
     *     description="User's facebook id. Provided by facebook. Unique",
     *     required=true
     * )
     *
     * @SWG\Response(
     *     response=201,
     *     description="Manually create a new user with the facebookId. Success",
     *     @Model(type=User::class)
     * )
     * @SWG\Response(
     *     response=400,
     *     description="Invalid data sent or missing field(s)"
     * )
     * @SWG\Response(
     *     response=403,
     *     description="You don't have the permission to access this URL. Login or signup, you need a valid access token."
     * )
     * @SWG\Tag(name="Users")
     */
    public function createAction(User $user, ConstraintViolationList $violations)
    {
        if (count($violations))
        {
            $message = "The JSON sent contains invalid data: ";
            foreach ($violations as $violation)
            {
                $message .= sprintf(
                    "Field %s: %s",
                    $violation->getPropertyPath(),
                    $violation->getMessage()
                );
            }
            throw new ResourceValidationException($message);
        }

        $em = $this->getDoctrine()->getManager();
        $em->persist($user);
        $em->flush();

        return $this->redirectToRoute('app_users_list');
    }

    // READ
    /**
     * @Get(
     *     path="/api/users",
     *     name="app_users_list"
     * )
     *
     * @View(StatusCode=200)
     *
     * @Security("has_role('ROLE_USER')")
     *
     * @SWG\Response(
     *     response=200,
     *     description="Users list.",
     *     @Model(type=User::class)
     * )
     * @SWG\Response(
     *     response=403,
     *     description="You don't have the permission to access this URL. Login or signup, you need a valid access token."
     * )
     * @SWG\Tag(name="Users")
     */
    public function listAction()
    {
        $users = $this->getDoctrine()
            ->getRepository('FacebookConnectionBundle:User')
            ->findAll();
        $data = $this->get('jms_serializer')
            ->serialize(
                $users,
                'json'
            );

        $response = new Response($data);
        $response->headers
            ->set('Content-Type', 'application/json');

        return $response;
    }

    /**
     * @Get(
     *     path="/api/users/{username}",
     *     name="app_user_show"
     * )
     * @View(StatusCode=200)
     *
     * @Security("has_role('ROLE_USER')")
     *
     * @param User $user
     * @return User
     * @throws
     *
     * @SWG\Parameter(
     *     name="username",
     *     in="query",
     *     type="string",
     *     description="Unique username to identify the user.",
     *     required=true
     * )
     *
     * @SWG\Response(
     *     response=200,
     *     description="User's detail.",
     *     @Model(type=User::class)
     * )
     * @SWG\Response(
     *     response=403,
     *     description="You don't have the permission to access this URL. Login or signup, you need a valid access token."
     * )
     * @SWG\Tag(name="Users")
     */
    public function showAction(User $user)
    {
        return $user;
    }

    /**
     * @Delete(
     *     path="/api/delete/{username}",
     *     name="app_user_delete"
     * )
     * @View(StatusCode=200)
     *
     * @Security("has_role('ROLE_USER')")
     *
     * @param User $user
     * @return mixed
     *
     * @SWG\Parameter(
     *     name="username",
     *     in="query",
     *     type="string",
     *     description="Unique username to identify the user.",
     *     required=true
     * )
     *
     * @SWG\Response(
     *     response=200,
     *     description="Delete an user. Success.",
     *     @Model(type=User::class)
     * )
     * @SWG\Response(
     *     response=403,
     *     description="You don't have the permission to access this URL. Login or signup, you need a valid access token."
     * )
     * @SWG\Tag(name="Users")
     */
    public function deleteAction(User $user)
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($user);
        $em->flush();

        return $this->redirectToRoute('app_users_list');
    }
}